export const UPDATE_REPO_DATA = 'UPDATE_REPO_DATA';
export const UPDATE_README_CONTENT = 'UPDATE_README_CONTENT';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const LOAD_REPO_DATA = 'LOAD_REPO_DATA';
export const SET_IS_AUTH_VALIDATED = 'SET_IS_AUTH_VALIDATED';
export const USER_LOGOUT = 'USER_LOGOUT';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';